# Project: sat
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = display.o "../新建文件夹\ (3)/未命名3.o"
LINKOBJ  = display.o "../新建文件夹 (3)/未命名3.o"
LIBS     = -L"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/lib" -L"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/include" -I"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/include" -I"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/BaiduNetdiskDownload/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = sat.exe
CXXFLAGS = $(CXXINCS) -g3 -std=c++11
CFLAGS   = $(INCS) -g3 -std=c++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

display.o: display.cpp
	$(CC) -c display.cpp -o display.o $(CFLAGS)

"../新建文件夹\ (3)/未命名3.o": ../新建文件夹\ (3)/未命名3.cpp
	$(CC) -c "../新建文件夹 (3)/未命名3.cpp" -o "../新建文件夹 (3)/未命名3.o" $(CFLAGS)
